stages:
  - build
  - deploy

default:
  tags:
    - builder

variables:
  app_name: makeline-service
  ARGO_REPO: http://${git_user}:${git_password}@gitlab.avl.home/k8s/argo_repo.git

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /.*-dev/
      variables:
        contour: dev
    - if: $CI_COMMIT_TAG =~ /.*-release/
      variables:
        contour: prod

build:
  stage: build
  script:
    - echo build
    - docker login -u ${harbor_user} -p ${harbor_password} ${harbor_url}
    - docker build -t ${harbor_url}/aks/${app_name}:${CI_COMMIT_TAG} .
    - docker push ${harbor_url}/aks/${app_name}:${CI_COMMIT_TAG}

deploy:
  stage: deploy
  when: manual
  script:
    - echo deploy
    - mkdir $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - git init --initial-branch=main
    - git remote add origin $ARGO_REPO
    - git pull origin main
    - cd $app_name/$contour
    - pwd
    - |
      sed -i "s|image: harbor.avl.home.*|image: harbor.avl.home/aks/makeline-service:$CI_COMMIT_TAG|g" ${app_name}.yaml
    - cat ${app_name}.yaml
    - git commit -am "version $CI_COMMIT_TAG to $contour"
    - git push origin main